import test from 'node:test';import assert from 'node:assert/strict';
import {parsePath,parseTransform,transformShape} from '../dist/js/svg-import.js';
import {artShapes,bbox,commands} from '../dist/js/geometry.js';
import {validateProject,validateShape} from '../dist/js/validation.js';
import {example,clone} from '../dist/js/model.js';import {svgExport,pdfExport} from '../dist/js/exports.js';import {setup} from './setup.mjs';setup();
test('SVG relative and smooth curves normalize to exact absolute Bezier controls',()=>{const cs=parsePath('M10 20 c 0 10 10 10 10 0 s 10 -10 10 0 q 5 10 10 0 t10 0 z');assert.deepEqual(cs[1],{type:'C',x1:10,y1:30,x2:20,y2:30,x:20,y:20});assert.deepEqual(cs[2],{type:'C',x1:20,y1:10,x2:30,y2:10,x:30,y:20});assert.equal(cs[4].y1,10);assert.equal(cs.at(-1).type,'Z');validateShape({type:'path',commands:cs});});
test('nested affine order, rotation pivot and nonuniform circles preserve physical placement',()=>{const m=parseTransform('translate(10 20) rotate(90) scale(2 3)'),s=transformShape({type:'circle',d:2,x:0,y:0},m),b=bbox(commands(s));assert.ok(Math.abs(b.x-7)<1e-5);assert.ok(Math.abs(b.y-18)<1e-5);assert.ok(Math.abs(b.w-6)<1e-5);assert.ok(Math.abs(b.h-4)<1e-5);const p=transformShape({type:'polygon',points:[{x:20,y:10},{x:10,y:10},{x:10,y:20}]},parseTransform('rotate(90 10 10)'));assert.ok(Math.abs(p.points[0].y-20)<1e-6);});
test('elliptical arc endpoints and malformed or collapsed input',()=>{const cs=parsePath('M0 0 A10 5 0 0 1 20 0');assert.equal(cs.at(-1).x,20);assert.equal(cs.at(-1).y,0);const b=bbox(cs);assert.ok(Math.abs(b.w-20)<.001);assert.ok(Math.abs(b.h-5)<.001);for(const s of ['M0','L0 0','M0 0 C1 2','M0 0 R2 3','M0 0 A1 2 0 4 0 1 1'])assert.throws(()=>parsePath(s));assert.throws(()=>parseTransform('scale(0)'));assert.throws(()=>parseTransform('translate(foo)'));});
test('numeric and custom scale legends are outlined in SVG/PDF and validate ranges',async()=>{const p=example(),a=p.panels[0].artwork.find(a=>a.type==='rotary');Object.assign(a,{labelMode:'numeric',labelMin:0,labelMax:10,labelEvery:2,labelDecimals:1,labelSuffix:' V',majorEvery:2,legendSize:3,legendGap:2});validateProject(p);assert.equal(artShapes(a,p).length,17);const svg=svgExport(p,p.panels[0]);assert.doesNotMatch(svg,/<text\b/);assert.ok((await pdfExport(p,p.panels[0],{pdfMode:'sheet'})).length>1000);a.labelMode='custom';a.customLabels=Array(11).fill('OFF');validateProject(p);const bad=clone(p);bad.panels[0].artwork.find(a=>a.type==='rotary').customLabels.pop();assert.throws(()=>validateProject(bad),/one custom/);});
