/* Transaction-contract fault injection. Browser IndexedDB QA is still required. */
import test from 'node:test';import assert from 'node:assert/strict';import {ProjectStore} from '../dist/js/storage.js';import {newProject,clone} from '../dist/js/model.js';
class Transaction {constructor(db,names,mode){this.db=db;this.names=Array.isArray(names)?names:[names];this.mode=mode;this.data=new Map([...db.data].map(([k,m])=>[k,new Map([...m].map(([k,v])=>[k,clone(v)]))]));this.pending=0;this.done=false;queueMicrotask(()=>this.finish());}abort(){this.done=true;queueMicrotask(()=>this.onabort?.());}finish(){if(this.done||this.pending)return;this.done=true;if(this.mode==='readwrite'){if(this.db.fail){this.error=Object.assign(Error('Injected storage failure'),{name:this.db.fail});this.db.fail=null;this.onabort?.();return;}for(const n of this.names)this.db.data.set(n,this.data.get(n));}this.oncomplete?.();}objectStore(name){const tx=this;return {get(id){const r={};tx.pending++;queueMicrotask(()=>{r.result=clone(tx.data.get(name).get(id));r.onsuccess?.();tx.pending--;tx.finish();});return r;},getAll(){const r={};tx.pending++;queueMicrotask(()=>{r.result=clone([...tx.data.get(name).values()]);r.onsuccess?.();tx.pending--;tx.finish();});return r;},put(v){tx.data.get(name).set(v.id,clone(v));}};}}
class FakeDB {constructor(){this.data=new Map(['projects','recovery','settings','library','history'].map(s=>[s,new Map()]));}transaction(names,mode='readonly'){return new Transaction(this,names,mode);}}
const make=db=>{const s=new ProjectStore();s.db=db;s.channel?.close();s.channel=null;return s;};
test('successful save and load increment generation; snapshots retain last good state',async()=>{const db=new FakeDB(),s=make(db),p=newProject();await s.save(p);p.name='second';await s.save(p);assert.equal((await s.load(p.id)).name,'second');assert.equal((await s.all('recovery'))[0].project.name,'Untitled contraption');assert.equal(s.seq.get(p.id),2);});
test('interrupted and quota-failed writes leave previous save intact',async()=>{for(const failure of ['AbortError','QuotaExceededError']){const db=new FakeDB(),s=make(db),p=newProject();await s.save(p);p.name='must not persist';db.fail=failure;await assert.rejects(s.save(p));assert.equal((await s.load(p.id)).name,'Untitled contraption');assert.equal((await s.all('recovery')).length,0);assert.equal(s.seq.get(p.id),1);}});
test('second writer cannot overwrite an unseen newer generation',async()=>{const db=new FakeDB(),a=make(db),b=make(db),p=newProject();await a.save(p);const copy=await b.load(p.id);p.name='newer';await a.save(p);copy.name='stale';await assert.rejects(b.save(copy),e=>e.code==='CONFLICT');assert.equal((await a.load(p.id)).name,'newer');});
test('recovery storage is bounded to ten previous successful saves',async()=>{const db=new FakeDB(),s=make(db),p=newProject();for(let i=0;i<16;i++){p.name='save '+i;await s.save(p);}const rows=await s.all('recovery');assert.equal(rows.length,10);assert.equal(Math.min(...rows.map(r=>r.seq)),6);assert.equal(Math.max(...rows.map(r=>r.seq)),15);});
