/* XML-tree integration, not browser DOM/layout verification. xml-js is a dev-only parser. */
import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {importSVG} from '../dist/js/validation.js';
let require=createRequire(import.meta.url),xml;try{xml=require('xml-js');}catch{if(!process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES)throw Error('Run npm install to install the dev-only XML test parser.');xml=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/xml-js');}
class Node{constructor(el){this.localName=el.name;this.attrs=el.attributes||{};this.attributes=Object.entries(this.attrs).map(([name,value])=>({name,value}));this.children=(el.elements||[]).filter(e=>e.type==='element').map(e=>new Node(e));}getAttribute(k){return this.attrs[k]??null;}querySelectorAll(){return this.children.flatMap(c=>[c,...c.querySelectorAll()]);}}
globalThis.DOMParser=class{parseFromString(text){try{const parsed=xml.xml2js(text),root=parsed.elements.filter(e=>e.type==='element');if(root.length!==1)throw Error('Multiple roots');return {documentElement:new Node(root[0]),querySelector:()=>null};}catch{return {querySelector:()=>({}),documentElement:{}};}}};
const svg=body=>`<svg xmlns="http://www.w3.org/2000/svg" width="100mm" height="80mm" viewBox="0 0 100 80">${body}</svg>`;
test('SVG document nesting composes transforms and preserves physical circles',()=>{const a=importSVG(svg('<g transform="translate(20 30)"><g transform="scale(2)"><circle cx="1" cy="2" r="3"/></g></g>'));assert.deepEqual(a.shapes[0],{type:'circle',x:22,y:34,d:12});assert.equal(a.w,100);const r=importSVG(svg('<rect x="10" y="20" width="5" height="8" rx="1"/>'));assert.equal(r.shapes[0].type,'rect');assert.equal(r.shapes[0].x,12.5);});
test('SVG accepts curved compound artwork, physical inch scale, ellipse, skew and open paths',()=>{const a=importSVG(svg('<g transform="skewX(10)"><path d="M0 0 Q5 10 10 0 T20 0"/><ellipse cx="30" cy="30" rx="5" ry="3"/></g>'));assert.equal(a.shapes.length,2);assert.equal(a.shapes[0].commands[1].type,'Q');const inches=importSVG('<svg width="1in" height="1in" viewBox="0 0 96 96"><circle cx="48" cy="48" r="24"/></svg>');assert.ok(Math.abs(inches.shapes[0].d-12.7)<1e-8);});
test('SVG rejects scripts, remote content, CSS, entities, malformed coordinates and singular transforms',()=>{for(const bad of ['<script>alert(1)</script>','<image href="https://x"/>','<use href="#x"/>','<circle r="2" style="display:none"/>','<circle r="2" onclick="x"/>','<circle r="2" fill="url(#x)"/>','<circle r="NaN"/>','<g transform="scale(0)"><circle r="2"/></g>','<rect width="-3" height="3"/>'])assert.throws(()=>importSVG(svg(bad)),bad);assert.throws(()=>importSVG('<!DOCTYPE svg [<!ENTITY x SYSTEM "file:///etc/passwd">]>'+svg('<circle r="2"/>')));assert.throws(()=>importSVG('<svg><circle>'));});
