/* Headless DOM-contract tests, NOT a substitute for browser interaction or visual QA. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {setup} from './setup.mjs';import {example,clone} from '../dist/js/model.js';
setup();
class Element {constructor(){this.dataset={};this.style={setProperty(){}};this.listeners={};this.classList={add(){},remove(){},toggle(){},contains(){return false;}};this.clientWidth=1000;this.clientHeight=700;this.value='';this.innerHTML='';this.hidden=false;this.open=false;this.files=[];this.type='text';}addEventListener(k,f){this.listeners[k]=f;}setAttribute(k,v){this[k]=v;}querySelector(){return new Element();}showModal(){this.open=true;}close(){this.open=false;}focus(){}click(){}getBoundingClientRect(){return {left:0,top:0,width:1000,height:700};}}
const nodes=new Map();const node=key=>{if(!nodes.has(key))nodes.set(key,new Element());return nodes.get(key);};const listeners={};globalThis.document={querySelector:node,querySelectorAll:()=>[],getElementById:id=>node('#'+id),documentElement:new Element(),body:new Element(),hidden:false,addEventListener:(k,f)=>listeners[k]=f,createElement:()=>new Element()};globalThis.window=globalThis;globalThis.addEventListener=()=>{};globalThis.innerWidth=1440;globalThis.requestAnimationFrame=fn=>setTimeout(fn,0);globalThis.location={protocol:'http:',reload(){}};globalThis.fetch=async()=>({ok:true,arrayBuffer:async()=>{const b=fs.readFileSync(new URL('../dist/fonts/DejaVuSans.ttf',import.meta.url));return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);}});
await import('../dist/js/app.js');await new Promise(r=>setTimeout(r,25));const api=globalThis.INTERFACEBENCH;const realTimeout=globalThis.setTimeout;globalThis.setTimeout=(fn,ms,...args)=>{const t=realTimeout(fn,ms,...args);if(ms>1000)t.unref();return t;};test.after(()=>api.store.channel?.close());const act=(name,dataset={})=>api.action(name,{dataset});
test('app boots and renders welcome without storage, using an explicit backup-needed status',()=>{assert.match(node('#dialogContent').innerHTML,/Give your/);assert.match(node('#saveState').textContent,/Backup needed/);});
test('example render produces canvas, library, inspector; precise edit, duplicate, rotate and undo retain model',async()=>{await api.openProject(example());const a=api.app;assert.match(node('#leftContent').innerHTML,/COMPONENT LIBRARY/);assert.match(node('#canvas').innerHTML,/data-object/);const id=a.panel.components[0].id;api.select([id]);const orig=a.panel.components.length;await act('duplicate');assert.equal(a.panel.components.length,orig+1);await act('undo');assert.equal(a.panel.components.length,orig);api.select([id]);await act('rotate');assert.equal(a.panel.components.find(c=>c.id===id).rotation,90);await act('undo');assert.equal(a.panel.components.find(c=>c.id===id).rotation,0);});
test('numeric edit validates and unit display changes never mutate dimensions',async()=>{const a=api.app;api.select([a.panel.components[0].id]);listeners.change({target:{dataset:{field:'object.x'},value:'0.5 in'}});assert.equal(a.panel.components[0].x,12.7);const s=JSON.stringify(a.p);listeners.change({target:{id:'units',value:'in',type:'select-one',dataset:{}}});assert.equal(JSON.stringify(a.p),s);});
test('every main stage renders and rehearsal leaves geometry unchanged',async()=>{await api.openProject(example());const before=JSON.stringify(api.app.p);for(const stage of ['define','arrange','connect','rehearse','fabricate']){await act('stage',{stage});if(stage==='connect')assert.match(node('#stageSurface').innerHTML,/wireBody/);if(stage==='fabricate')assert.match(node('#stageSurface').innerHTML,/Create fabrication ZIP/);}assert.equal(JSON.stringify(api.app.p),before);});
test('custom definition dialog actually contains dimension and terminals controls',async()=>{api.select([api.app.panel.components[0].id]);await act('edit-definition');assert.match(node('#dialogContent').innerHTML,/name="openings"/);assert.match(node('#dialogContent').innerHTML,/name="rearW"/);assert.match(node('#dialogContent').innerHTML,/name="terminals"/);await act('close');});
test('malformed project import does not replace current project; imported baseline survives',async()=>{const before=JSON.stringify(api.app.p);await assert.rejects(api.readFile(new File(['{"bad":true}'],'bad.json',{type:'application/json'}),'project'));assert.equal(JSON.stringify(api.app.p),before);const p=example(),snapshot=clone(p);p.baselines.push({id:'baseline-test',name:'A',date:'2026-10-08',snapshot});await api.readFile(new File([JSON.stringify(p)],'p.json',{type:'application/json'}),'project');assert.equal(api.app.p.baselines.length,1);});
test('locks protect numeric fields, transforms and deletion; multi-selection arrangement works',async()=>{await api.openProject(example());const a=api.app,id=a.panel.components[0].id;api.select([id]);await act('lock');const before=clone(a.panel.components[0]);await act('rotate');await act('delete');assert.deepEqual(a.panel.components[0],before);await act('lock');api.select(a.panel.components.slice(0,3).map(c=>c.id));await act('align',{kind:'cy'});assert.equal(new Set(a.panel.components.slice(0,3).map(c=>c.y)).size,1);});
async function submitValues(form,values){const Original=globalThis.FormData;globalThis.FormData=class{constructor(){}[Symbol.iterator](){return Object.entries(values)[Symbol.iterator]();}};try{return await api.submit({dataset:{form}});}finally{globalThis.FormData=Original;}}
test('terminal table rename preserves IDs and wiring through definition submit and undo',async()=>{await api.openProject(example());api.select([api.app.panel.components[0].id]);await act('edit-definition');const c=clone(api.app.panel.components[0]),d=c.definition,original=clone(api.app.p.connections);listeners.change({target:{dataset:{terminal:'name',index:'0'},value:'Renamed SDA',type:'text'}});const values={name:d.name,kind:d.kind,prefix:d.prefix,mountReference:d.mountReference,source:d.source,notes:d.notes,verifiedDate:d.verifiedDate,depth:d.depth,bend:d.bend,minThickness:d.minThickness,maxThickness:d.maxThickness,openings:JSON.stringify(d.openings)};for(const k of ['front','rear','access'])Object.assign(values,{[k+'Type']:d[k].type,[k+'W']:d[k].d||d[k].w,[k+'H']:d[k].h||d[k].d,[k+'R']:d[k].r||0});await submitValues('definition',values);assert.equal(api.app.panel.components[0].definition.terminals[0].name,'Renamed SDA');assert.deepEqual(api.app.p.connections,original);await act('undo');assert.equal(api.app.panel.components[0].definition.terminals[0].name,d.terminals[0].name);});
test('sourced presets, scale legend dialog and library revision apply are reachable',async()=>{await api.openProject(example());api.select([api.app.panel.components[0].id]);await act('controller');node('#m-profile').value='nano-every';await act('controller-preset');assert.equal(node('#m-name').value,'Arduino Nano Every');assert.match(node('#m-pins').value,/A7,A7,5/);await act('close');const a=api.app.panel.artwork.find(a=>a.type==='rotary');api.select([a.id]);await act('legend');assert.match(node('#dialogContent').innerHTML,/Custom labels/);await submitValues('legend',{labelMode:'numeric',labelPrefix:'',labelSuffix:' V',labelMin:'0',labelMax:'10',labelDecimals:'0',labelEvery:'2',majorEvery:'2',legendSize:'3',legendGap:'2',majorLength:'4',minorLength:'2',customLabels:''});assert.equal(api.app.panel.artwork.find(x=>x.id===a.id).labelMode,'numeric');api.select([api.app.panel.components[0].id]);await act('save-library');await submitValues('save-library',{saveKind:'revision',revisionNote:'Reviewed dimensions'});const saved=api.app.library.at(-1);await act('library-updates');assert.match(node('#dialogContent').innerHTML,/Apply r/);await act('apply-revision',{id:saved.id});assert.equal(api.app.panel.components[0].definition.id,saved.id);await act('undo');assert.notEqual(api.app.panel.components[0].definition.id,saved.id);});
test('companion import previews without mutation, applies atomically and is undoable',async()=>{await api.openProject(example());const before=JSON.stringify(api.app.p),file=new File([fs.readFileSync(new URL('./fixtures/copperbench-schema5.json',import.meta.url))],'board.json');await api.readFile(file,'copperbench');assert.equal(JSON.stringify(api.app.p),before);assert.match(node('#dialogContent').innerHTML,/mounting/);await submitValues('handoff-import',{});assert.equal(api.app.p.panels.length,2);await act('undo');assert.equal(JSON.stringify(api.app.p.panels),JSON.stringify(JSON.parse(before).panels));await act('interchange');assert.match(node('#dialogContent').innerHTML,/PINNOTE/);await act('handoff-export',{target:'pinnote'});assert.match(node('#dialogContent').innerHTML,/Wire lengths/);await act('close');});
