/* Deterministic documentation generated from the exact shipped catalog. */
import fs from 'node:fs';
import {builtinParts,categories,partCategory,sourceLabel,openingSummary,shapeSummary} from '../src/js/component-library.js';
import {VERSION,esc} from '../src/js/model.js';
import {partIcon} from '../src/js/canvas.js';
const summary=categories.map(([id,name])=>({id,name,parts:builtinParts.filter(d=>partCategory(d)===id)}));
const md=['# Component catalog',`\nINTERFACEBENCH ${VERSION}: **${builtinParts.length} components in ${categories.length} categories**. Expanded from 12 to 267: 255 additional generic definitions.`,
  '\n265 generic planning templates and 2 manufacturer-sourced E-Switch definitions. Generic dimensions, terminal topology and panel limits are illustrative. They are not measured footprints or manufacturer ratings. Even sourced parts retain explicit clearance assumptions. Measure your selected hardware before fabrication.',
  '\n## Find and reuse a part',
  '\nChoose a category, search by name, terminal family, size or a tag (for example `USB type C`, `fader 100`, `MIDI`, or `M3 standoff 20`). Multiple search words must all match; words match from their start. Filter generic, sourced, custom or favorites. The first 24 matches appear; Show more adds 24. Search and filters survive placement and selection. Favorites are saved in workspace preferences when local storage is available.',
  '\nDetails shows front/rear/access sizes, every opening with its offset, thickness/depth allowances, terminals, provenance and rehearsal model before placement. Click a card to place immediately, or Place component in Details. Edit definition changes an embedded instance; Save to library creates a reusable revision. Category and comma-separated tags are editable.',
  '\n## Interpretation',
  '\n- Connector-family names (USB, IEC, D-sub, GX, etc.) identify planning use, not certified mating or mounting geometry. Rectangular apertures can approximate shaped or keyed cutouts; replace them with measured geometry before manufacturing.\n- P1…Pn terminals are placeholders, not a verified pinout. Passive 0 V means unspecified; active 5 V terminals are example logic assumptions.\n- Generic carriers do not claim compatibility with a particular board. Hole pitch must be measured or imported through COPPERBENCH.\n- Buttons, toggles, pots, encoders and displays use existing interaction models. Complex sensors, connectors and modules provide geometry and wiring records only; no device protocol, circuit simulation or firmware driver is added.\n- Physical component definitions embed in project JSON. Updating the catalog does not silently replace existing project geometry. Legacy schema 1–3 projects and library version 1–2 imports remain supported.',
  '\n| Category | Components |\n| --- | ---: |',...summary.map(c=>`| ${c.name} | ${c.parts.length} |`)];
for(const c of summary)md.push(`\n## ${c.name}`, '\n| Part | Source | Front mm | Cutouts mm | Terminals | ID |\n| --- | --- | --- | --- | ---: | --- |',...c.parts.map(d=>`| ${d.name} | ${sourceLabel(d)} | ${shapeSummary(d.front)} | ${openingSummary(d)} | ${d.terminals.length} | \`${d.id}\` |`));
fs.writeFileSync('docs/COMPONENT-CATALOG.md',md.join('\n')+'\n');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>INTERFACEBENCH ${VERSION} · Component catalog</title><style>
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f4f5ed;color:#22392c;font:15px/1.6 system-ui,sans-serif}header,main,footer{max-width:1220px;margin:auto;padding:32px}header{padding-top:55px;border-bottom:1px solid #b6c5ac}h1{font-size:clamp(28px,5vw,48px);line-height:1.1;letter-spacing:-1.5px;margin:18px 0}h2{margin:32px 0 12px}p{max-width:900px}a{color:#315e32}nav{display:flex;gap:8px;flex-wrap:wrap;margin-top:24px}nav a{padding:6px 12px;background:#e4ead9;border-radius:5px;text-decoration:none;font-size:12px}.eyebrow{letter-spacing:2px;font-size:11px;font-weight:700}.metrics{display:flex;gap:36px;margin:28px 0}.metrics strong{font-size:35px;display:block}.metrics small{font-size:12px}.note{padding:16px 20px;background:#e6ead8;border-left:4px solid #5a793c}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:12px}.card{border:1px solid #b8c6b1;border-radius:8px;padding:16px;background:#fffef5;break-inside:avoid}.card svg{display:block;width:100%;height:90px;background:#182b21;border-radius:6px;padding:10px}.card h3{font-size:15px;line-height:1.4;min-height:42px;margin:14px 0 8px}.card small{display:block;color:#526650}.badge{display:inline-block;font-size:10px;letter-spacing:1px;text-transform:uppercase;border:1px solid #b9c8af;border-radius:4px;padding:2px 7px;margin:10px 0 0}.card p{font-size:12px;margin:6px 0}.card details{font-size:12px;overflow-wrap:anywhere}.card summary{cursor:pointer}table{border-collapse:collapse;width:100%;font-size:13px}td,th{text-align:left;border-bottom:1px solid #c4cfbd;padding:8px}footer{font-size:12px;border-top:1px solid #b6c5ac}@media print{nav{display:none}body{background:white}.grid{grid-template-columns:repeat(3,1fr)}header,main,footer{padding:10px}.card{font-size:10px}.card svg{height:70px}details{display:none}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}</style></head><body>
<header><div class="eyebrow">GREEN SHOE GARAGE · INTERFACEBENCH ${VERSION}</div><h1>A much bigger parts bench.</h1><p>Physical interface planning, from a 3 mm indicator to a 120 mm fan opening. Browse the exact catalog bundled with this release.</p><div class="metrics"><div><strong>267</strong><small>total components</small></div><div><strong>255</strong><small>new templates</small></div><div><strong>14</strong><small>categories</small></div></div><p class="note"><strong>Planning templates require measurement.</strong> 265 definitions are generic; 2 retain manufacturer-source evidence. Generic dimensions, holes, terminal identities and ratings are unverified. Connector-family names indicate intended use, not a certified footprint.</p><nav>${summary.map(c=>`<a href="#${c.id}">${esc(c.name)} · ${c.parts.length}</a>`).join('')}</nav></header>
<main><section><h2>What changed</h2><p>Category and source filters, word-based search, saved favorites, dimension details before placement, and editable custom categories/tags make the larger library practical. Browsing shows 24 results at a time and preserves filters when you place a component.</p><p><strong>64 automated checks pass.</strong> Every definition validates, embeds independently, round-trips through project JSON and exports its openings. Generic cut patterns are checked for internal overlap and containment. Complex patterns also pass PDF and frozen-ZIP export checks.</p><p><strong>Release candidate:</strong> actual browser layout, pointer/keyboard behavior, persistence and offline/update acceptance remain unverified. The Sites skill requires skipping browser QA when its supported browser-control skill is unavailable and forbids a substitute browser path. This report is a generated catalog reference, not a browser screenshot or a physical measurement report.</p><p>Complex connectors, sensors and modules supply geometry and wiring documentation only. P-number terminals are placeholders; passive 0 V means unspecified. Existing interaction models support simple controls and readouts, not circuit simulation.</p></section>
${summary.map(c=>`<section id="${c.id}"><h2>${esc(c.name)} <small>(${c.parts.length})</small></h2><div class="grid">${c.parts.map(d=>`<article class="card">${partIcon(d)}<span class="badge">${sourceLabel(d)}</span><h3>${esc(d.name)}</h3><p><strong>Front:</strong> ${esc(shapeSummary(d.front))} mm</p><p><strong>Cut:</strong> ${esc(openingSummary(d))}</p><small>${d.depth} mm rear depth · ${d.terminals.length} terminals · ${d.openings.length} opening${d.openings.length===1?'':'s'}</small><details><summary>Definition notes</summary><p>${esc(d.source)}</p><p>${esc(d.notes)}</p><p>Rear: ${esc(shapeSummary(d.rear))} mm. Access: ${esc(shapeSummary(d.access))} mm. Panel: ${d.minThickness}–${d.maxThickness} mm.</p><p>Opening offsets: ${d.openings.map(s=>`${esc(shapeSummary(s))} at (${s.x||0}, ${s.y||0})`).join('; ')} mm.</p><small>${esc(d.id)}</small></details></article>`).join('')}</div></section>`).join('')}
</main><footer>INTERFACEBENCH ${VERSION} · 2026-10-09 · GPL-3.0-only · No telemetry or external assets. Source definitions: js/component-library.js and js/catalog.js. Existing projects retain embedded dimensions.</footer></body></html>`;
fs.writeFileSync('src/CATALOG.html',html);
fs.mkdirSync('../output',{recursive:true});
fs.writeFileSync(`../output/INTERFACEBENCH-v${VERSION}-release-report.html`,html);
fs.writeFileSync('qa/catalog-summary.json',JSON.stringify({version:VERSION,total:builtinParts.length,added:255,generic:265,sourced:2,categories:summary.map(({id,name,parts})=>({id,name,count:parts.length}))},null,2)+'\n');
console.log(`Documented ${builtinParts.length} components in ${categories.length} categories.`);
